[package]
name = "onerom-studio"
version = "0.1.2"
edition = "2024"
authors = ["Piers Finlayson <piers@piers.rocks>"]
license = "MIT"
description = "One ROM Studio - Manage One ROM, the most flexible retro ROM replacement"
repository = "https://github.com/piersfinlayson/one-rom"
homepage = "https://onerom.org"
documentation = "https://docs.rs/onerom-gen"
keywords = ["retro", "rom", "commodore", "embedded"]
categories = ["embedded", "hardware-support"]

[[bin]]
name = "onerom-studio"
path = "src/main.rs"

# Packager configuration - creates bundles and isntallers
[package.metadata.packager]
enabled = true
name = "onerom-studio"
product_name = "One ROM Studio"
publisher = "piers.rocks"
authors = ["Piers Finlayson"]
identifier = "rocks.piers.onerom-studio"
license-file = "LICENSE.txt"
homepage = "https://onerom.org"
description = "One ROM Studio" 
longDescription = "One ROM Studio - Manage One ROM, the most flexible retro ROM replacement"
formats = ["dmg", "nsis", "deb"]
icons = ["assets/onerom-512x512.png", "assets/onerom-256x256.png", "assets/onerom-128x128.png", "assets/onerom-64x64.png", "assets/onerom-32x32.png", "assets/onerom-16x16.png", "assets/onerom.ico"]
out-dir = "./dist"

# Windows installer
[package.metadata.packager.nsis]
installer-mode = "currentUser"
header-image = "assets/onerom-header.bmp"
sidebar-image = "assets/onerom-sidebar.bmp"
installer-icon = "assets/onerom.ico"
display-language-selector = false

# Linux package
[package.metadata.packager.linux]
generate-desktop-entry = true
[package.metadata.packager.deb]
files = { "scripts/70-onerom-studio.rules" = "/lib/udev/rules.d/70-onerom-studio.rules" }

# Cargo bundle metadata, used on macOS (not cargo packager)
[package.metadata.bundle]
name = "One ROM Studio"
identifier = "rocks.piers.onerom-studio"
icon = ["assets/onerom-512x512.png", "assets/onerom-256x256.png", "assets/onerom-128x128.png", "assets/onerom-64x64.png", "assets/onerom-32x32.png", "assets/onerom-16x16.png"]
short_description = "One ROM Studio"
long_description = "One ROM Studio - Manage One ROM, the most flexible retro ROM replacement"
osx_minimum_system_version = "10.13"

[dependencies]
onerom-config = { path = "../config", version = "0.2.2" }
onerom-fw = { path = "../fw", version = "0.1.1" }
onerom-gen = { path = "../gen", version = "0.2.0" }
sdrr-fw-parser = { path = "../sdrr-fw-parser", version = "0.5.4" }
dfu-rs = { git = "https://github.com/piersfinlayson/dfu-rs.git", version = "0.2.0" }

chrono = "0.4"
futures = "0.3"
iced = { version = "0.13", features = ["tokio", "image"] }
log = "0.4"
open = "5.3"
probe-rs = { version = "0.29", features = [] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "charset"] }
resvg = "0.45"
rfd = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny-skia = "0.11"
tokio = { version = "1", features = ["rt"] }
usvg = "0.45"

[build-dependencies]
built = { version = "0.8", features = ["git2"] }
git2 = { version = "0.20", default-features = false }
embed-resource = "3"
