// Copyright (C) 2026 Piers Finlayson <piers@piers.rocks>
//
// MIT License

// Handle loading and testing of images

#include <stdio.h>
#include <include.h>
#include <apio.h>
#include <epio.h>
#include <test/stub.h>
#include <test/func.h>

typedef struct {
    // When the firmware inputs are generated, ROMs are indexed starting at 0,
    // for example output/images/0.rom, 1.rom, etc.  This is that index.
    uint8_t build_index;

    // The index of the set of ROM images this ROM image apples to.  The
    // firmware generator starts with set 0, image 0, then moves to set 0,
    // image 1, etc. 
    uint8_t set_index;

    // The index of the image within the set.
    uint8_t image_index;

    uint8_t pad;

    // The actual ROM image data, loaded from the file generated by sdrr-gen.
    uint8_t *data;
} test_src_rom_image_t;

// Array of pointers to ROM sources images, index by the build_index.
#define TST_MAX_ROM_IMAGES 64
_Static_assert(TST_MAX_ROM_IMAGES < 256, "TST_MAX_ROM_IMAGES must be less than 256 to fit in build_index");
static test_src_rom_image_t src_rom_images[TST_MAX_ROM_IMAGES];

#define TST_MAX_ROM_IMAGE_SIZE  (512*1024)

#define OUTPUT_IMAGE_DIR "../output/images"

static void load_src_rom_images(void) {
    memset(src_rom_images, 0, sizeof(src_rom_images));

    uint8_t next_set_index = 0;
    uint8_t next_image_index = 0;
    uint8_t total_sets = SDRR_NUM_SETS;
    uint8_t total_images = SDRR_NUM_IMAGES;
    for (int ii = 0; ii < total_images; ii++) {
        assert(next_set_index < total_sets && "More ROM images than expected");

        // Open the image
        char filename[256];
        snprintf(filename, sizeof(filename), "%s/%d.rom", OUTPUT_IMAGE_DIR, ii);
        FILE *file = fopen(filename, "rb");
        assert(file && "Failed to open ROM image file");

        // Get the file size
        fseek(file, 0, SEEK_END);
        long file_size = ftell(file);
        fseek(file, 0, SEEK_SET);
        assert(file_size <= TST_MAX_ROM_IMAGE_SIZE && "ROM image is too large");

        // Read the file into memory
        uint8_t *buffer = malloc(file_size);
        assert(buffer && "Failed to allocate memory for ROM image");
        fread(buffer, 1, file_size, file);
        fclose(file);

        // Store the image data and metadata
        src_rom_images[ii].build_index = ii;
        src_rom_images[ii].set_index = next_set_index;
        src_rom_images[ii].image_index = next_image_index;
        src_rom_images[ii].data = buffer;

        TST_LOG("Loaded ROM image: %s (set %d image %d size %ld bytes)", filename, next_set_index, next_image_index, file_size);

        // Figure out the next set and image index
        next_image_index++;
        if (next_image_index >= rom_set[next_set_index].rom_count) {
            next_image_index = 0;
            next_set_index++;
        }
    }

    if ((next_set_index == 0) && (next_image_index == 0)) {
        TST_LOG("No ROM images loaded\n");
    }
}

void setup_rom_images(void) {
    load_src_rom_images();
}

// Get the appropriate ROM image data for a given set and image index.
const uint8_t *get_src_rom_image_data(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    test_src_rom_image_t *image = &src_rom_images[set_index * SDRR_NUM_IMAGES + image_index];
    assert(image->set_index == set_index && image->image_index == image_index && "ROM image metadata mismatch");
    uint8_t *data = image->data;
    assert(data != NULL && "ROM image data is NULL");
    return data;
}

sdrr_rom_type_t get_rom_type(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    const sdrr_rom_info_t *rom_info = rom_set[set_index].roms[image_index];
    assert(rom_info->rom_type < NUM_CHIP_TYPES && "Invalid ROM type");
    return rom_info->rom_type;
}

uint32_t get_rom_image_size(uint8_t set_index, uint8_t image_index) {
    assert(set_index < SDRR_NUM_SETS && "Set index out of range");
    assert(image_index < rom_set[set_index].rom_count && "Image index out of range");
    const sdrr_rom_info_t *rom_info = rom_set[set_index].roms[image_index];
    assert(rom_info->rom_type < NUM_CHIP_TYPES && "Invalid ROM type");
    return chip_size_from_type[rom_info->rom_type];
}

uint8_t get_rom_image_data_byte(uint8_t set_index, uint8_t image_index, uint32_t addr) {
    const uint8_t *data = get_src_rom_image_data(set_index, image_index);
    assert(data != NULL && "ROM image data is NULL");
    uint32_t size = get_rom_image_size(set_index, image_index);
    assert(addr < size && "Address out of range for ROM image");
    return data[addr];
}