# Workspace configuration for the Rust elements of the One ROM project
[workspace]
members = [
    "config",
    "database",
    "fw",
    "gen",
    "lab",
    "sdrr-check",
    "sdrr-fw-parser",
    "sdrr-gen",
    "sdrr-info",
    "studio"
]
default-members = [
    "config",
    "sdrr-fw-parser",
    "sdrr-gen",
    "sdrr-info"
]
resolver = "2"