#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules
            udevadm trigger --action=add
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0