[package]
name = "lab"
version = "0.4.1"
edition = "2024"
authors = ["Piers Finlayson <piers@piers.rocks>"]
description = "One ROM Lab firmware"
repository = "https://github.com/piersfinlayson/one-rom"
readme = "README.md"
license = "MIT"
keywords = ["embedded", "rom", "eeprom", "eprom", "flash"]

[[bin]]
name = "onerom-lab"
path = "src/main.rs"

[features]
default = [ "embassy-stm32/stm32f405rg" ]

[dependencies]
defmt = { version = "1.0", features = [ "alloc" ] }
embassy-executor = { version = "0.9.0", features = ["executor-thread", "arch-cortex-m", "defmt", "nightly" ]}
embassy-futures = { version = "0.1.1", features = ["defmt"] }
embassy-stm32 = { version = "0.4.0", features = [ "memory-x", "time-driver-any", "unstable-pac", "exti", "defmt" ]}
embassy-sync = { version = "0.7.0" }
embassy-time = { version = "0.5", features = [ "tick-hz-32_768", "defmt" ] }
embedded-alloc = { version = "0.6" }
portable-atomic = { version = "1.10", features = [ "critical-section" ] }
cortex-m = { version = "0.7.6", features = [ "critical-section-single-core" ] }
cortex-m-rt = { version = "0.7.0"}
panic-probe = { version = "1.0", features = [ "print-defmt" ]}
static_cell = { version = "2.1", features = [ "nightly" ] }
defmt-rtt = { version = "1.0"}
embedded-hal = { version = "1.0.0"}
critical-section = { version = "1.2.0" }
hex = { version = "0.4", default-features = false, features = [ "alloc" ] }
hex-literal = "1.0.0"
sha1 = { version = "0.10", default-features = false }
